name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
env:
  ENV_FILE: "lambda-dev.json"


jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: JSON to variables
        uses: antifree/json-to-variables@HEAD
        with:
          filename: ${{ env.ENV_FILE }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy lambda 01
        uses: appleboy/lambda-action@master
        with:
          function_name: ${{ env.json_lambda1_name }}
          source: ${{ env.json_lambda1_source }}
      - name: deploy lambda 02
        uses: appleboy/lambda-action@master
        with:
          function_name: ${{ env.json_lambda2_name }}
          source: ${{ env.json_lambda2_source }}