name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  lambdaMatrix: |
    - lambda-cd: "function.py"
    - lambda-cd-02: "function-02.py"

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: echo 123
        run: |
          echo ${{ env.lambdaMatrix }}
    # steps:
    #   - name: checkout source code
    #     uses: actions/checkout@v1
    #   - name: deploy lambda 01
    #     uses: appleboy/lambda-action@master
    #     with:
    #       aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws_region: ${{ secrets.AWS_REGION }}
    #       function_name: lambda-cd
    #       source: function.py
    #   - name: deploy lambda 02
    #     uses: appleboy/lambda-action@master
    #     with:
    #       aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws_region: ${{ secrets.AWS_REGION }}
    #       function_name: lambda-cd-02
    #       source: function-02.py