name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: JSON to variables
        uses: antifree/json-to-variables@HEAD
        with:
          filename: 'test.json'
          prefix: env
      - name: Show output
        run: echo "The time was ${{ env.env_dev_lambda1_name }}"
      - name: deploy lambda 01
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ env.env_dev_lambda1_name }}
          source: ${{ env.env_dev_lambda1_source }}
      # - name: deploy lambda 02
      #   uses: appleboy/lambda-action@master
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: ${{ secrets.AWS_REGION }}
      #     function_name: ${{ env.env_dev_lambda2_name }}
      #     source: ${{ env.env_dev_lambda2_source }}