name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda-name: [lambda-cd, lambda-cd-02]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      # - name: Zip files 
      #   uses: vimtor/action-zip@v1
      #   with:
      #     files: ${{ matrix.lambda-name }}
      #     dest: ${{ matrix.lambda-name }}.zip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy lambda 01
        uses: appleboy/lambda-action@master
        with:
          function_name: ${{ matrix.lambda-name }}
          source: ${{ matrix.lambda-name }}